# https://docs.readthedocs.io/en/latest/yaml-config.html
version: 2

formats:
  - htmlzip
  - epub

python:
  version: 3.7
  install:
    - requirements: docs-requirements.txt

sphinx:
  fail_on_warning: true
